server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank-account-db
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

axon:
  amqp:
    exchange: bank-account.events
  eventhandling:
    processors:
      amqpEvents:
        source: complaintEventsMethod